services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra_ent
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=ENT_CLUSTER

  minio:
    image: minio/minio
    container_name: minio_ent
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"